# using mysql image
FROM mysql:8.0

# setting environment varialbles for mysql
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# exposing port for db
EXPOSE 3306
